version: '3'

services:
  db:
    image: postgres:13
    command: postgres -c log_statement=all
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adviserapi
    ports:
      - 54327:5432

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - CHAT_GPT_KEY=${CHAT_GPT_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: