# Generated by Django 4.2 on 2023-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisermessages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='advisermessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
